<?php

namespace Database\Seeders;

use App\Models\Categoria;
use App\Models\Produto;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProdutosSeeder extends Seeder
{
    public function run()
    {
        // Categorias existentes (SEM mudar lógica)
        $camisetas = Categoria::where('slug', 'camisetas')->first();
        $user  = User::first();

        if (!$user) {
            $this->call(UserSeeder::class);
            $user = User::first();
        }

        $blusas    = Categoria::where('slug', 'blusas')->first();
        $bone      = Categoria::where('slug', 'bone')->first();
        $casacos   = Categoria::where('slug', 'casacos')->first();
        $shorts    = Categoria::where('slug', 'shorts')->first();

        if (!$camisetas || !$blusas || !$bone || !$casacos || !$shorts) {
            $this->call(CategoriasSeeder::class);

            $camisetas = Categoria::where('slug', 'camisetas')->first();
            $blusas    = Categoria::where('slug', 'blusas')->first();
            $bone      = Categoria::where('slug', 'bone')->first();
            $casacos   = Categoria::where('slug', 'casacos')->first();
            $shorts    = Categoria::where('slug', 'shorts')->first();
        }

        $produtos = [

            /* ================= CAMISETAS (20 produtos) ================= */
            [
                'nome' => 'Camiseta Básica Preta Essential',
                'descricao' => 'Camiseta de algodão 100%, confortável e durável. Ideal para uso diário.',
                'preco' => 49.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 50,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Branca Minimal',
                'descricao' => 'Visual clean para qualquer ocasião. Tecido leve e respirável.',
                'preco' => 54.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 40,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Oversized Street',
                'descricao' => 'Modelagem oversized moderna com caimento perfeito. Estilo urbano.',
                'preco' => 69.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 35,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Preta Slim Fit',
                'descricao' => 'Caimento ajustado e tecido respirável. Perfeita para looks elegantes.',
                'preco' => 55.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 45,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Azul Marinho Básica',
                'descricao' => 'Cor versátil que combina com tudo. Algodão premium.',
                'preco' => 52.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 38,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Cinza Melange',
                'descricao' => 'Efeito mescla sofisticado. Toque macio e confortável.',
                'preco' => 57.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 42,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Estampada Street Art',
                'descricao' => 'Estampa exclusiva com arte urbana. Edição limitada.',
                'preco' => 79.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 25,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Listrada Navy',
                'descricao' => 'Estilo clássico com listras. Perfeita para looks despojados.',
                'preco' => 64.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 32,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Vinho Básica',
                'descricao' => 'Tonalidade vinho elegante. 100% algodão penteado.',
                'preco' => 54.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 37,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Off-White Premium',
                'descricao' => 'Tom off-white sofisticado. Acabamento reforçado.',
                'preco' => 59.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 44,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Verde Militar',
                'descricao' => 'Tom verde militar. Estilo urbano e resistente.',
                'preco' => 57.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 33,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Amarela Mustarda',
                'descricao' => 'Cor mustarda estilosa. Destaque no visual.',
                'preco' => 62.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 28,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Estampada Retrô',
                'descricao' => 'Estampa com elementos retrô anos 80/90.',
                'preco' => 74.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 26,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Animal Print',
                'descricao' => 'Estampa animal print moderna. Estilo ousado.',
                'preco' => 69.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 23,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Tie Dye Colorida',
                'descricao' => 'Efeito tie dye psicodélico. Peça única.',
                'preco' => 79.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 21,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta UV Protect',
                'descricao' => 'Proteção UV 50+. Ideal para dias de sol.',
                'preco' => 89.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 29,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Dry Fit Preta',
                'descricao' => 'Tecido que absorve o suor. Perfeita para exercícios.',
                'preco' => 69.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 48,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Dry Fit Branca',
                'descricao' => 'Alta performance. Secagem rápida.',
                'preco' => 69.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 46,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Gola V Preta',
                'descricao' => 'Gola V moderna. Caimento diferenciado.',
                'preco' => 59.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 39,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],
            [
                'nome' => 'Camiseta Gola V Branca',
                'descricao' => 'Modelo gola V básico. Algodão premium.',
                'preco' => 59.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 41,
                'user_id' => $user->id,
                'categoria_id' => $camisetas->id,
            ],

            /* ================= BLUSAS (20 produtos) ================= */
            [
                'nome' => 'Blusa de Moletom Premium',
                'descricao' => 'Moletom flanelado de alta qualidade. Aquecimento e conforto.',
                'preco' => 199.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 25,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa Canguru Street',
                'descricao' => 'Blusa com capuz e bolso frontal. Estilo urbano e funcional.',
                'preco' => 179.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 30,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Cinza',
                'descricao' => 'Moletom confortável para dias frios. Algodão soft.',
                'preco' => 169.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 28,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa Com Zíper Integral',
                'descricao' => 'Modelo com zíper frontal. Versátil e moderna.',
                'preco' => 189.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 22,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Vinho',
                'descricao' => 'Cor vinho elegante. Forrada e super quente.',
                'preco' => 199.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 19,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa Canguru Estampada',
                'descricao' => 'Estampa exclusiva com capuz ajustável.',
                'preco' => 209.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 18,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Azul Marinho',
                'descricao' => 'Clássico azul marinho. Ideal para o inverno.',
                'preco' => 189.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 27,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa com Capuz Oversized',
                'descricao' => 'Modelagem oversized para máximo conforto. Super macia.',
                'preco' => 219.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 16,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Off-White',
                'descricao' => 'Tom off-white sofisticado. Detalhes em bordado.',
                'preco' => 194.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 23,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa Canguru Básica Preta',
                'descricao' => 'Clássica preta com bolso canguru. Indispensável.',
                'preco' => 179.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 35,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Vermelha',
                'descricao' => 'Vermelho vibrante. Estilo descolado.',
                'preco' => 189.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 21,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Verde Musgo',
                'descricao' => 'Tom verde musgo elegante. Aconchegante.',
                'preco' => 199.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 20,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa Canguru Tie Dye',
                'descricao' => 'Efeito tie dye colorido. Modelo canguru.',
                'preco' => 229.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 15,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Com Estampa',
                'descricao' => 'Estampa frontal exclusiva. Moletom soft.',
                'preco' => 209.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 22,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Com Bolso',
                'descricao' => 'Bolso canguru amplo. Capuz com cordão.',
                'preco' => 194.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 26,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Slim',
                'descricao' => 'Modelagem slim. Visual mais ajustado.',
                'preco' => 199.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 24,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Camuflada',
                'descricao' => 'Estampa camuflada moderna. Estilo militar.',
                'preco' => 219.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 17,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Com Zíper',
                'descricao' => 'Meio zíper frontal. Gola alta.',
                'preco' => 199.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 23,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Cropada',
                'descricao' => 'Modelo croped. Moderno e despojado.',
                'preco' => 179.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 28,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],
            [
                'nome' => 'Blusa de Moletom Infantojuvenil',
                'descricao' => 'Tamanho infantojuvenil. Qualidade premium.',
                'preco' => 159.90,
                'imagem' => 'images/produtos/01KHY4JXDRR21TRFCA7S3B40R3.jpeg',
                'estoque' => 32,
                'user_id' => $user->id,
                'categoria_id' => $blusas->id,
            ],

            /* ================= BONÉS (20 produtos) ================= */
            [
                'nome' => 'Boné Snapback Preto',
                'descricao' => 'Boné ajustável com design urbano. Aba reta.',
                'preco' => 79.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 35,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Dad Hat Bege',
                'descricao' => 'Estilo casual com aba curva. Toque retrô.',
                'preco' => 69.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 40,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Snapback Azul',
                'descricao' => 'Azul vibrante com ajuste snap. Estrutura moderna.',
                'preco' => 79.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 32,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Trucker Mesh',
                'descricao' => 'Tela mesh atrás para ventilação. Estilo americano.',
                'preco' => 59.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 45,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Camuflado Urbano',
                'descricao' => 'Estampa camuflada moderna. Ajuste por velcro.',
                'preco' => 74.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 28,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Branco Básico',
                'descricao' => 'Branco clean. Combina com tudo.',
                'preco' => 69.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 38,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Snapback Vermelho',
                'descricao' => 'Vermelho vibrante para looks descolados.',
                'preco' => 79.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 31,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Dad Hat Preto',
                'descricao' => 'Dad hat preto clássico. Aba curvada natural.',
                'preco' => 69.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 42,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Verde Militar',
                'descricao' => 'Tom verde militar. Estrutura resistente.',
                'preco' => 74.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 33,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Tie Dye Colorido',
                'descricao' => 'Estampa tie dye exclusiva. Modelo ajustável.',
                'preco' => 84.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 22,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Snapback Rosa',
                'descricao' => 'Rosa suave. Estilo urbano.',
                'preco' => 79.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 27,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Snapback Amarelo',
                'descricao' => 'Amarelo vibrante. Destaque no visual.',
                'preco' => 79.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 26,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Dad Hat Jeans',
                'descricao' => 'Tecido jeans. Estilo casual.',
                'preco' => 74.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 34,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Trucker Vermelho',
                'descricao' => 'Vermelho com tela mesh. Estilo americano.',
                'preco' => 59.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 39,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Com Rótulo',
                'descricao' => 'Detalhe de rótulo frontal. Estilo autêntico.',
                'preco' => 69.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 36,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Corduroy Marrom',
                'descricao' => 'Tecido corduroy. Textura diferenciada.',
                'preco' => 89.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 21,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Floral Estampado',
                'descricao' => 'Estampa floral. Primavera/verão.',
                'preco' => 79.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 25,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Lettering Bordado',
                'descricao' => 'Bordado com lettering exclusivo.',
                'preco' => 84.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 29,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Neon Verde',
                'descricao' => 'Cor neon. Destaca-se em qualquer look.',
                'preco' => 69.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 30,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],
            [
                'nome' => 'Boné Neon Laranja',
                'descricao' => 'Laranja fluorescente. Estilo ousado.',
                'preco' => 69.90,
                'imagem' => 'images/produtos/01KHY4PDF0C7581N5ES03ZT0J3.jpeg',
                'estoque' => 28,
                'user_id' => $user->id,
                'categoria_id' => $bone->id,
            ],

            /* ================= CASACOS (20 produtos) ================= */
            [
                'nome' => 'Casaco Jeans Slim',
                'descricao' => 'Casaco jeans com lavagem premium. Modelagem ajustada.',
                'preco' => 249.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 20,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Casaco Puffer Inverno',
                'descricao' => 'Casaco térmico ideal para dias frios. Super quente.',
                'preco' => 329.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 15,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Casaco Jeans Oversized',
                'descricao' => 'Modelagem oversized. Jeans lavagem escura.',
                'preco' => 269.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 18,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Jaqueta Bomber Preta',
                'descricao' => 'Estilo bomber clássico. Punho e barra canelada.',
                'preco' => 289.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 22,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Casaco de Lã Premium',
                'descricao' => 'Lã de alta qualidade. Perfeito para ocasiões especiais.',
                'preco' => 399.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 12,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Jaqueta Corta Vento',
                'descricao' => 'Resistente à água e vento. Ideal para trilhas.',
                'preco' => 259.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 25,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Casaco Jeans Destroyed',
                'descricao' => 'Jeans com detalhes destroyed. Estilo despojado.',
                'preco' => 279.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 17,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Parka Inverno com Capuz',
                'descricao' => 'Parka longa com forro removível. Super quente.',
                'preco' => 449.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 10,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Casaco de Moletom com Zíper',
                'descricao' => 'Casaco moletom com zíper. Confortável e prático.',
                'preco' => 199.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 28,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Jaqueta Jeans Clássica',
                'descricao' => 'Modelo clássico jeans. Nunca sai de moda.',
                'preco' => 239.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 24,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Jaqueta de Couro Sintético',
                'descricao' => 'Estilo rocker. Couro sintético de qualidade.',
                'preco' => 349.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 14,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Casaco Trench Coat',
                'descricao' => 'Elegante trench coat. Visual sofisticado.',
                'preco' => 389.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 11,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Jaqueta Sarja Bege',
                'descricao' => 'Sarja resistente. Modelo casual.',
                'preco' => 229.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 23,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Casaco de Lã Xadrez',
                'descricao' => 'Estampa xadrez clássica. Lã premium.',
                'preco' => 419.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 9,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Jaqueta Bomber Verde Militar',
                'descricao' => 'Bomber verde. Estilo militar moderno.',
                'preco' => 299.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 19,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Casaco Puffer Azul Marinho',
                'descricao' => 'Puffer azul marinho. Aquecimento extremo.',
                'preco' => 339.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 13,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Jaqueta Jeans Com Pelúcia',
                'descricao' => 'Jeans com forro de pelúcia. Quente e estiloso.',
                'preco' => 289.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 16,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Casaco Moletom Com Capuz',
                'descricao' => 'Moletom com capuz. Casual e confortável.',
                'preco' => 219.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 27,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Jaqueta Corta Vento Azul',
                'descricao' => 'Azul vibrante. Resistente à água.',
                'preco' => 269.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 21,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],
            [
                'nome' => 'Casaco de Lã Cinza',
                'descricao' => 'Lã cinza elegante. Corte moderno.',
                'preco' => 379.90,
                'imagem' => 'images/produtos/01KHY5B141N8QF7P7RW47NV1BN.png',
                'estoque' => 12,
                'user_id' => $user->id,
                'categoria_id' => $casacos->id,
            ],

            /* ================= SHORTS (20 produtos) ================= */
            [
                'nome' => 'Shorts Moletom Confort',
                'descricao' => 'Shorts confortável para o dia a dia. Elástico na cintura.',
                'preco' => 89.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 45,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Jeans Destroyed',
                'descricao' => 'Visual moderno com lavagem estonada e barra desfiada.',
                'preco' => 119.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 30,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Tactel Esportivo',
                'descricao' => 'Tecido leve e secagem rápida. Ideal para esportes.',
                'preco' => 79.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 52,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Jeans Azul Claro',
                'descricao' => 'Jeans claro lavagem stone. Modelo casual.',
                'preco' => 109.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 34,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Moletom Cinza',
                'descricao' => 'Moletom cinza com bolsos laterais. Super confortável.',
                'preco' => 89.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 41,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Sarja Bege',
                'descricao' => 'Tecido sarja resistente. Modelo social casual.',
                'preco' => 99.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 36,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Jeans Preto',
                'descricao' => 'Jeans preto versátil. Combina com tudo.',
                'preco' => 114.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 38,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Bermuda Cargo',
                'descricao' => 'Estilo cargo com bolsos laterais. Algodão resistente.',
                'preco' => 129.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 27,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Moletom Preto',
                'descricao' => 'Preto básico com bolsos. Conforto total.',
                'preco' => 89.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 44,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Jeans Rasgado',
                'descricao' => 'Modelo com rasgos estratégicos. Estilo descolado.',
                'preco' => 124.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 29,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Tactel Preto',
                'descricao' => 'Tactel preto. Leve e prático.',
                'preco' => 79.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 48,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Tactel Azul',
                'descricao' => 'Azul marinho. Ideal para atividades físicas.',
                'preco' => 79.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 47,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Sarja Cáqui',
                'descricao' => 'Tom cáqui. Estilo social casual.',
                'preco' => 99.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 35,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Jeans Claro Rasgado',
                'descricao' => 'Jeans claro com detalhes rasgados.',
                'preco' => 119.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 31,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Moletom Vermelho',
                'descricao' => 'Vermelho vibrante. Conforto e estilo.',
                'preco' => 94.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 33,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Moletom Azul Marinho',
                'descricao' => 'Azul marinho. Clássico e versátil.',
                'preco' => 89.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 40,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Jeans Destroyed Azul',
                'descricao' => 'Destroyed azul claro. Estilo moderno.',
                'preco' => 124.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 26,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Jeans Destroyed Preto',
                'descricao' => 'Destroyed preto. Visual ousado.',
                'preco' => 124.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 28,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Bermuda Tactel',
                'descricao' => 'Bermuda em tactel. Modelagem ampla.',
                'preco' => 89.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 43,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
            [
                'nome' => 'Shorts Moletom Com Bolsos',
                'descricao' => 'Bolsos laterais funcionais. Conforto total.',
                'preco' => 94.90,
                'imagem' => 'images/produtos/01KHY72ASEQC8KN4DQDMK5BPVS.jpeg',
                'estoque' => 39,
                'user_id' => $user->id,
                'categoria_id' => $shorts->id,
            ],
        ];

        foreach ($produtos as $produto) {
            $produto['slug'] = Str::slug($produto['nome']);
            Produto::create($produto);
        }
    }
}